services:
    base:
        profiles: [srsran]
        image: o5gc/srsran-project
        entrypoint: ["/mnt/srsran/entrypoint.sh"]
        env_file: ["${ENV_FILE}"]
        labels:
            o5gc.stack: ${O5GC_STACK}
            o5gc.webui.priority: ${WEBUI_PRIO_RAN}
        volumes:
            - ${DOCKER}/srsran/project/:/mnt/srsran/:ro
            - ${DEVELOP_VOLUME_SRSRAN:-${BASE}/var/empty:/var/empty}
        privileged: true

    gnb:
        extends:
            service: base
        container_name: gnb
        profiles: ["gnb"]
        command: gnb
        privileged: true
        environment:
            - DOCKER_TARGET_HOSTNAME=${GNB_HOSTNAME}
        volumes:
            - ${BASE}/scripts/docker-remote.sh:/docker-remote.sh:ro
            - ${BASE}:/tmp/o5gc:ro
            - ${HOME}/.ssh:/mnt/.ssh:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /dev/bus/usb:/dev/bus/usb
        networks:
            rfnet:
                ipv4_address: ${GNB_RF_IP_ADDR}
            corenet:
                ipv4_address: ${GNB_IP_ADDR}
        labels:
            o5gc.webui.priority: ${WEBUI_PRIO_CORE_HIGH}
