logger:
    file:
      path: /var/log/open5gs/amf.log
    level: ${OPEN5GS_LOGLEVEL}

sbi:
    server:
      no_tls: true
    client:
      no_tls: true

global:
  max:
    ue: 1024

amf:
    sbi:
      server:
        - address: ${AMF_IP_ADDR}
          port: 7777
      client:
        nrf:
          - uri: http://${NRF_IP_ADDR}:7777
        scp:
          - uri: http://${SCP_IP_ADDR}:7777
    ngap:
      server:
        - address: ${AMF_IP_ADDR}
    guami:
      - plmn_id:
          mcc: ${MCC}
          mnc: ${MNC}
        amf_id:
          region: 2
          set: 1
    tai:
      - plmn_id:
          mcc: ${MCC}
          mnc: ${MNC}
        tac: ${TAC}
    plmn_support:
      - plmn_id:
          mcc: ${MCC}
          mnc: ${MNC}
        s_nssai:
          - sst: ${NSSAI_SST}
            sd: ${NSSAI_SD}
    security:
        integrity_order : [ NIA2, NIA1, NIA0 ]
        ciphering_order : [ NEA2, NEA1, NEA0 ]
    network_name:
        full: Open5GS
    amf_name: open5gs-amf
    metrics:
      server:
        - address: ${AMF_IP_ADDR}
          port: 9091
    time:
      t3512:
        value: 540
