logger:
    file:
      path: /var/log/open5gs/ausf.log
    level: ${OPEN5GS_LOGLEVEL}

sbi:
    server:
      no_tls: true
    client:
      no_tls: true

global:
  max:
    ue: 1024

ausf:
    sbi:
      server:
        - address: ${AUSF_IP_ADDR}
          port: 7777
      client:
        nrf:
          - uri: http://${NRF_IP_ADDR}:7777
        scp:
          - uri: http://${SCP_IP_ADDR}:7777
