logger:
    file:
      path: /var/log/open5gs/nrf.log
    level: ${OPEN5GS_LOGLEVEL}

sbi:
    server:
      no_tls: true
    client:
      no_tls: true

global:
  max:
    ue: 1024

nrf:
    serving:  # 5G roaming requires PLMN in NRF
      - plmn_id:
          mcc: ${MCC}
          mnc: ${MNC}
    sbi:
      server:
      - address: ${NRF_IP_ADDR}
        port: 7777
