logger:
    file:
      path: /var/log/open5gs/nssf.log
    level: ${OPEN5GS_LOGLEVEL}

sbi:
    server:
      no_tls: true
    client:
      no_tls: true

global:
  max:
    ue: 1024

nssf:
    sbi:
      server:
        - address: ${NSSF_IP_ADDR}
          port: 7777
      client:
        nrf:
          - uri: http://${NRF_IP_ADDR}:7777
        scp:
          - uri: http://${SCP_IP_ADDR}:7777
        nsi:
          - uri: http://${NRF_IP_ADDR}:7777
            s_nssai:
              sst: ${NSSAI_SST}
              sd: ${NSSAI_SD}
