db_uri: ${DB_URI}

logger:
    file:
      path: /var/log/open5gs/pcrf.log
    level: ${OPEN5GS_LOGLEVEL}

global:
  max:
    ue: 1024

pcrf:
    freeDiameter: /open5gs/install/etc/freeDiameter/pcrf.conf
