logger:
    file:
      path: /var/log/open5gs/scp.log
    level: ${OPEN5GS_LOGLEVEL}

sbi:
    server:
      no_tls: true
    client:
      no_tls: true

global:
  max:
    ue: 1024

scp:
    sbi:
      server:
        - address: ${SCP_IP_ADDR}
          port: 7777
      client:
        nrf:
          - uri: http://${NRF_IP_ADDR}:7777
