mcc: '${MCC}'          # Mobile Country Code value
mnc: '${MNC}'          # Mobile Network Code value (2 or 3 digits)

nci: '${NR_CELL_ID}'  # NR Cell Identity (36-bit)
idLength: 32       # NR gNB ID length in bits [22...32]
tac: ${TAC}        # Tracking Area Code

linkIp: ${GNB_RF_IP_ADDR}  # gNB's local IP address for Radio Link Simulation
ngapIp: ${GNB_IP_ADDR}     # gNB's local IP address for N2 Interface
gtpIp: ${GNB_IP_ADDR}      # gNB's local IP address for N3 Interface

# List of AMF address information
amfConfigs:
  - address: ${AMF_IP_ADDR}
    port: 38412

# List of supported S-NSSAIs by this gNB
slices:
  - sst: ${NSSAI_SST}
    sd: ${NSSAI_SD}

# Indicates whether or not SCTP stream number errors should be ignored.
ignoreStreamIds: true
