# IMSI number of the UE. IMSI = [MCC|MNC|MSISDN] (In total 15 digits)
supi: 'imsi-${MCC}${MNC}${UE_SOFT_MSIN}'
# Mobile Country Code value of HPLMN
mcc: '${MCC}'
# Mobile Network Code value of HPLMN (2 or 3 digits)
mnc: '${MNC}'

# Permanent subscription key
key: '${UE_SOFT_KEY}'
# Operator code (OP or OPC) of the UE
op: '${UE_SOFT_OPC}'
# This value specifies the OP type and it can be either 'OP' or 'OPC'
opType: 'OPC'
# Authentication Management Field (AMF) value
amf: '8000'
# IMEI number of the device. It is used if no SUPI is provided
imei: '356938035643803'
# IMEISV number of the device. It is used if no SUPI and IMEI is provided
imeiSv: '4370816125816151'

# List of gNB IP addresses for Radio Link Simulation
gnbSearchList:
  - ${GNB_RF_IP_ADDR}

# UAC Access Identities Configuration
uacAic:
  mps: false
  mcs: false

# UAC Access Control Class
uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false

# Initial PDU sessions to be established
sessions:
  - type: 'IPv4'
    apn: '${APN}'
    slice:
      sst: ${NSSAI_SST}
      sd: ${NSSAI_SD}

# Configured NSSAI for this UE by HPLMN
configured-nssai:
  - sst: ${NSSAI_SST}
    sd: ${NSSAI_SD}

# Default Configured NSSAI for this UE
default-nssai:
  - sst: ${NSSAI_SST}
    sd: ${NSSAI_SD}

# Supported integrity algorithms by this UE
integrity:
  IA1: true
  IA2: true
  IA3: true

# Supported encryption algorithms by this UE
ciphering:
  EA1: true
  EA2: true
  EA3: true

# Integrity protection maximum data rate for user plane
integrityMaxRate:
  uplink: 'full'
  downlink: 'full'
