info:
  version: 1.0.3
  description: UDM initial local configuration

configuration:
  serviceNameList: # the SBI services provided by this UDM, refer to TS 29.503
    - nudm-sdm # Nudm_SubscriberDataManagement service
    - nudm-uecm # Nudm_UEContextManagement service
    - nudm-ueau # Nudm_UEAuthenticationManagement service
    - nudm-ee # Nudm_EventExposureManagement service
    - nudm-pp # Nudm_ParameterProvisionDataManagement service
  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: ${UDM_IP_ADDR} # IP used to register to NRF
    bindingIPv4: ${UDM_IP_ADDR}  # IP used to bind the service
    port: 7777 # Port used to bind the service
    tls: # the local path of TLS key
      pem: cert/udm.pem # UDM TLS Certificate
      key: cert/udm.key # UDM TLS Private key
  nrfUri: http://${NRF_IP_ADDR}:7777 # a valid URI of NRF

  # test data set from TS33501-f60 Annex C.4
  SuciProfile: # Home Network Public Key ID = slice index +1
    - ProtectionScheme: 1 # Protect Scheme: Profile A
      PrivateKey: e8dd07a20905557e2c029a724b42efa93a50424d306e0b68a334b0c2e9bc8863
      PublicKey: 28ea6090c84ba15d44cb19123a5d1a28c1aa560af6cad33f12afa660b821fa13
    - ProtectionScheme: 2 # Protect Scheme: Profile B
      PrivateKey: F1AB1074477EBCC7F554EA1C5FC368B1616730155E0041AC447D6301975FECDA
      PublicKey: 0472DA71976234CE833A6907425867B82E074D44EF907DFB4B3E21C1C2256EBCD15A7DED52FCBB097A4ED250E036C7B9C8C7004C4EEDC4F068CD7BF8D3F900E3B4

logger: # log output setting
  enable: true # true or false
  level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  reportCaller: false # enable the caller report or not, value: true or false
