info:
  version: 1.1.0
  description: UDR initial local configuration

configuration:
  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: ${UDR_IP_ADDR} # IP used to register to NRF
    bindingIPv4: ${UDR_IP_ADDR}  # IP used to bind the service
    port: 7777 # port used to bind the service
    tls: # the local path of TLS key
      pem: cert/udr.pem # UDR TLS Certificate
      key: cert/udr.key # UDR TLS Private key
  dbConnectorType: mongodb 
  mongodb:
    name: free5gc # Database name in MongoDB
    url: mongodb://${MONGO_IP_ADDR}:27017 # URL of MongoDB
  nrfUri: http://${NRF_IP_ADDR}:7777 # a valid URI of NRF
  nrfCertPem: cert/nrf.pem # NRF Certificate

logger: # log output setting
  enable: true # true or false
  level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  reportCaller: false # enable the caller report or not, value: true or false
