services:
    base:
        profiles: [srsran]
        image: o5gc/srsran-4g
        entrypoint: ["/mnt/srsran/entrypoint.sh"]
        env_file: ["${ENV_FILE}"]
        labels:
            o5gc.stack: ${O5GC_STACK}
            o5gc.webui.priority: ${WEBUI_PRIO_RAN}
        volumes:
            - .:/mnt/srsran/:ro
            - ${DEVELOP_VOLUME_SRSRAN:-${BASE}/var/empty:/var/empty}
        privileged: true

    epc:
        extends:
            service: base
        container_name: epc
        profiles: ["core"]
        labels:
            o5gc.webui.priority: ${WEBUI_PRIO_CORE_HIGH}
        command: epc
        networks:
            extnet:
                ipv4_address: ${EPC_EXT_IP_ADDR}  # eth0
            corenet:
                ipv4_address: ${EPC_IP_ADDR}  # eth1

    ran:
        extends:
            service: base
        profiles: ["ran"]
        volumes:
            - ${BASE}/scripts/docker-remote.sh:/docker-remote.sh:ro
            - ${BASE}:/tmp/o5gc:ro
            - ${HOME}/.ssh:/mnt/.ssh:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /dev/bus/usb:/dev/bus/usb
        environment:
            - UHD_IMAGE_LOADER

    enb:
        extends:
            service: ran
        container_name: enb
        profiles: ["enb"]
        command: enb
        environment:
            - DOCKER_TARGET_HOSTNAME=${ENB_HOSTNAME}
        networks:
            rfnet:
                ipv4_address: ${ENB_RF_IP_ADDR}
            corenet:
                ipv4_address: ${ENB_IP_ADDR}

    gnb:
        extends:
            service: ran
        container_name: gnb
        profiles: ["gnb"]
        command: gnb
        environment:
            - DOCKER_TARGET_HOSTNAME=${GNB_HOSTNAME}
        networks:
            rfnet:
                ipv4_address: ${GNB_RF_IP_ADDR}
            corenet:
                ipv4_address: ${GNB_IP_ADDR}

    ue:
        extends:
            service: base
        container_name: ue
        profiles: ["ue"]
        volumes:
            - /dev/bus/usb:/dev/bus/usb
        environment:
            - EUTRA_NOF_CARRIERS=0
            - NR_NOF_CARRIERS=0
            - RF_SRATE=11.52e6
        command: ue
        networks:
            rfnet:
                ipv4_address: ${UE_RF_IP_ADDR}

    develop:
        extends:
            file: ${DOCKER}/o5gc/services.yaml
            service: develop
        image: o5gc/srsran-4g:develop
        container_name: srsran-develop
        hostname: srsran-develop
